services:
    web:
        container_name: projetPEC
        build: .
        volumes:
            - ./app:/var/www/html
            - ./logs:/var/log/apache2/
        ports:
            - 8081:80
        depends_on:
            - db
    db:
        container_name: projetPEC-db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: "db"
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "password"
        ports:
            - 5444:5432
        volumes:
            - ./db_data:/var/lib/postgresql/data
            - ./db/init:/docker-entrypoint-initdb.d
volumes:
    db:
