services:
    web:
        container_name: projetPEC
        build: .
        volumes:
            - ./app:/var/www/html
            - ./logs:/var/log/apache2/
        ports:
            - 8081:80
        depends_on:
            - db
    db:
        container_name: projetPEC-db
        image: mysql:latest
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - 3308:3306
        volumes:
            - ./mysql:/var/lib/mysql
            - ./mysql/db:/docker-entrypoint-initdb.d
